import { NextRequest, NextResponse } from 'next/server';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

// Use real page images extracted from the example PDFs
const COLUMBUS_PHOTOS = [
  '/vistoria-exemplos/columbus/page_005.jpg',
  '/vistoria-exemplos/columbus/page_006.jpg',
  '/vistoria-exemplos/columbus/page_007.jpg',
  '/vistoria-exemplos/columbus/page_008.jpg',
  '/vistoria-exemplos/columbus/page_010.jpg',
  '/vistoria-exemplos/columbus/page_011.jpg',
  '/vistoria-exemplos/columbus/page_013.jpg',
  '/vistoria-exemplos/columbus/page_014.jpg',
];

const SAINTPETER_PHOTOS = [
  '/vistoria-exemplos/saintpeter/page_005.jpg',
  '/vistoria-exemplos/saintpeter/page_006.jpg',
  '/vistoria-exemplos/saintpeter/page_008.jpg',
  '/vistoria-exemplos/saintpeter/page_009.jpg',
  '/vistoria-exemplos/saintpeter/page_012.jpg',
  '/vistoria-exemplos/saintpeter/page_013.jpg',
  '/vistoria-exemplos/saintpeter/page_016.jpg',
  '/vistoria-exemplos/saintpeter/page_017.jpg',
  '/vistoria-exemplos/saintpeter/page_020.jpg',
  '/vistoria-exemplos/saintpeter/page_021.jpg',
  '/vistoria-exemplos/saintpeter/page_024.jpg',
  '/vistoria-exemplos/saintpeter/page_025.jpg',
  '/vistoria-exemplos/saintpeter/page_028.jpg',
  '/vistoria-exemplos/saintpeter/page_029.jpg',
  '/vistoria-exemplos/saintpeter/page_032.jpg',
  '/vistoria-exemplos/saintpeter/page_033.jpg',
  '/vistoria-exemplos/saintpeter/page_036.jpg',
  '/vistoria-exemplos/saintpeter/page_037.jpg',
  '/vistoria-exemplos/saintpeter/page_040.jpg',
  '/vistoria-exemplos/saintpeter/page_041.jpg',
];

function generateExample1() {
  return {
    condominio: 'EDIFÍCIO COLUMBUS TOWER I',
    endereco: 'Avenida Guilherme Dumont Villares',
    numero: '1.410',
    conjApto: 'Conj. 103',
    apto: '',
    andar: '',
    cep: '05640-003',
    bairro: 'Vila Suzana',
    cidade: 'São Paulo',
    estado: 'SP',
    tipoImovel: 'SALA',
    finalidade: 'COMERCIAL',
    metragem: '35m²',
    mobiliado: 'NÃO',
    locadora: 'ALEXANDRA LEONARDI ESCOBAR',
    locadoraCpf: '153.224.928-44',
    locadoraTelefone: '(11) 99876-5432',
    locatario: 'IGOR AUGUSTO MIRA',
    locatarioCpf: '277.246.018-52',
    locatarioTelefone: '(11) 98765-4321',
    vistoriadora: 'Mônica Barbosa',
    dataFotografia: '23/12/2025',
    dataLaudo: '27/12/2025',
    solicitante: 'ARTIMOB NEGÓCIOS IMOBILIÁRIOS',
    emailContestacao: 'monica@artimob.com',
    rooms: [
      {
        name: 'SALA',
        items: [
          '✓ 1 porta de entrada de madeira e batente na cor branca, bom estado com chaves',
          '✓ Fechadura de metal dourado com maçaneta e chaves funcionando em bom estado apresentando desgaste',
          '✓ 1 interfone em bom estado, porém não foi possível testar',
          '✓ 2 suportes para álcool em gel, sendo um do lado externo da sala e outro dentro',
          '✓ 1 caixa de luz em bom estado, funcionando',
          '✓ 2 caixas de fiação em bom estado',
          '✓ Paredes em alvenaria com pintura branca, em bom estado',
          '✓ Rodapé em madeira MDF branco em bom estado',
          '✓ Tomadas e interruptores de plástico em bom estado, funcionando',
          '✓ Janelas com vidros antirruídos em ótimo estado, funcionando',
          '✓ Persianas rolo em bom estado porém com algumas manchas',
          '✓ 4 gavetas em madeira branca abaixo das janelas em bom estado',
          '✓ Ar condicionado marca SAMSUNG – DIGITAL INVERTER, funcionando em bom estado',
          '✓ 1 controle remoto do ar condicionado, com pilha, funcionando em bom estado',
          '✓ Piso revestido em laminado marrom em bom estado',
          '✓ Teto em alvenaria revestido com forro de gesso branco em ótimo estado',
          '✓ 5 luminárias de embutir quadradas, brancas com lâmpadas em bom estado, funcionando',
        ],
        observations: 'A sala apresenta-se em bom estado geral. As persianas rolo apresentam algumas manchas que poderão ser limpas. O ar condicionado SAMSUNG funciona perfeitamente. As gavetas abaixo das janelas estão em bom estado mas com leve desgaste no puxador. Todas as tomadas e interruptores foram testados e estão funcionando.',
        photos: COLUMBUS_PHOTOS.slice(0, 4).map((url, i) => ({
          dataUrl: url, name: `sala_${i + 1}.jpg`,
          annotations: i === 2 ? [{ x: 35, y: 45, label: 'Manchas na persiana' }] : i === 3 ? [{ x: 60, y: 70, label: 'Desgaste na gaveta' }] : [],
        })),
      },
      {
        name: 'COPA',
        items: [
          '✓ Porta de entrada de madeira e batente na cor gelo, bom estado com chaves',
          '✓ Fechadura de metal dourado com maçaneta e chaves funcionando em bom estado apresentando desgaste',
          '✓ Paredes em alvenaria com pintura nova em bom estado com cano de água externo fixado',
          '✓ Janela de abrir de alumínio marrom com vidro em ótimo estado',
          '✓ Espelho grande fixado em bom estado',
          '✓ Pia de mármore em bom estado',
          '✓ Torneira alta preta flexível, em bom estado e funcionando',
          '✓ Sifão dourado em bom estado',
          '✓ Piso em mármore bege em bom estado apresentando desgastes',
          '✓ Ralo em bom estado',
          '✓ Teto branco rebaixado com gesso em bom estado',
          '✓ 1 luminária spot redonda de embutir com lâmpada funcionando em bom estado',
        ],
        observations: 'A copa está em bom estado. O piso de mármore apresenta desgastes naturais de uso. A fechadura da porta apresenta desgaste no metal dourado. A torneira flexível preta funciona perfeitamente. O espelho está fixado e sem danos.',
        photos: COLUMBUS_PHOTOS.slice(4, 6).map((url, i) => ({
          dataUrl: url, name: `copa_${i + 1}.jpg`,
          annotations: i === 1 ? [{ x: 40, y: 55, label: 'Desgaste no piso' }] : [],
        })),
      },
      {
        name: 'BANHEIRO',
        items: [
          '✓ Porta de entrada de madeira e batente na cor gelo, bom estado com chaves',
          '✓ Fechadura de metal dourado com maçaneta e chaves funcionando com muito desgaste',
          '✓ 1 vaso sanitário com caixa acoplada com tampa de plástico em bom estado, funcionando',
          '✓ 2 prateleiras fixadas de madeira branca em bom estado',
          '✓ Paredes em alvenaria pintura branca cinza e uma com revestimento de papel de parede, em bom estado',
          '✓ 1 registro de metal em bom estado',
          '✓ 1 lixeira de inox com pedal totalmente oxidada',
          '✓ 1 escova de limpeza de vaso com suporte de metal em estado regular',
          '✓ 1 espelho grande fixado em bom estado',
          '✓ 1 pia de mármore com cuba de louça bege em bom estado',
          '✓ 1 torneira de metal dourada com desgaste e funcionando',
          '✓ 1 gabinete de madeira branca em bom estado',
          '✓ 1 sifão dourado em bom estado',
          '✓ 2 suportes de papel de plástico em bom estado',
          '✓ Teto de alvenaria rebaixado em gesso na cor branca em bom estado',
          '✓ 1 luminária spot redonda em bom estado, com lâmpada funcionando',
          '✓ Piso de mármore em bom estado',
          '✓ 1 ralo em bom estado',
          '✓ Interruptor de plástico funcionando em bom estado',
        ],
        observations: 'O banheiro apresenta geralmente bom estado. A lixeira de inox está totalmente oxidada e deverá ser substituída. A escova de limpeza com suporte de metal está em estado regular. A fechadura da porta apresenta muito desgaste mas ainda funciona. A torneira de metal dourada funciona mas apresenta desgaste visível. O vaso sanitário e a pia estão em perfeito funcionamento.',
        photos: COLUMBUS_PHOTOS.slice(6, 8).map((url, i) => ({
          dataUrl: url, name: `banheiro_${i + 1}.jpg`,
          annotations: i === 0 ? [{ x: 50, y: 60, label: 'Lixeira oxidada' }] : i === 1 ? [{ x: 45, y: 40, label: 'Desgaste no metal dourado' }] : [],
        })),
      },
    ],
    consideracoes: 'Conforme laudo, o imóvel encontra-se em bom estado de conservação. O estado do imóvel foi relatado acima de forma textual. O imóvel está sendo entregue COM PINTURA NOVA nas paredes e deverá ser devolvido COM PINTURA NOVA no final da locação. Foram testadas torneiras, vasos sanitários, interruptores e constatado que a parte hidráulica e elétrica está em funcionamento. O ar condicionado foi testado e está funcionando.',
  };
}

function generateExample2() {
  return {
    condominio: 'CONDOMÍNIO EDIFÍCIO SAINT PIERRE',
    endereco: 'Rua Diogo Pereira',
    numero: '297',
    conjApto: '',
    apto: 'Apto 182',
    andar: '18º andar',
    cep: '05750-130',
    bairro: 'Super Quadra Morumbi',
    cidade: 'São Paulo',
    estado: 'SP',
    tipoImovel: 'APARTAMENTO',
    finalidade: 'RESIDENCIAL',
    metragem: '87m²',
    mobiliado: 'NÃO',
    locadora: 'MIYOCO HAYASHI DE ALMEIDA',
    locadoraCpf: '184.641.348-60',
    locadoraTelefone: '(11) 97654-3210',
    locatario: 'TUANI BATISTA DA SILVA',
    locatarioCpf: '135.693.136-70',
    locatarioTelefone: '(11) 96543-2109',
    vistoriadora: 'Mônica Barbosa',
    dataFotografia: '11/07/2026',
    dataLaudo: '13/07/2026',
    solicitante: 'ARTIMOB NEGÓCIOS IMOBILIÁRIOS LTDA',
    emailContestacao: 'monica@artimob.com',
    rooms: [
      {
        name: 'ENTRADA',
        items: [
          '✓ Porta da entrada principal e batente de madeira em bom estado com pintura branca',
          '✓ Fechadura de metal preta com maçaneta e chave funcionando em bom estado com manchas de tinta',
          '✓ Campainha não está funcionando',
          '✓ 1 capacho em bom estado',
          '✓ Paredes em alvenaria com pintura nova em bom estado',
          '✓ Caixa de distribuição elétrica com disjuntores em bom estado, funcionando',
          '✓ Porta chave decorativo de madeira com conchas em bom estado',
          '✓ Piso em cerâmica branco em bom estado',
          '✓ Rodapé em cerâmica branca em bom estado',
          '✓ Teto em alvenaria com pintura branca em bom estado',
          '✓ 1 luminária plafon de alumínio branco em bom estado com lâmpada funcionando e sujo',
          '✓ Interruptor de material plástico amarelado em bom estado, funcionando',
        ],
        photos: SAINTPETER_PHOTOS.slice(0, 2).map((url, i) => ({
          dataUrl: url, name: `entrada_${i + 1}.jpg`,
          annotations: i === 1 ? [{ x: 50, y: 50, label: 'Campainha não funciona' }] : [],
        })),
      },
      {
        name: 'SALA DE ESTAR E ESCRITÓRIO',
        items: [
          '✓ Porta de correr de alumínio com vidro em ótimo estado',
          '✓ Paredes em alvenaria com pintura nova em bom estado',
          '✓ Piso em porcelanato cinza em bom estado',
          '✓ Rodapé em porcelanato em bom estado',
          '✓ Teto com forro de gesso em bom estado',
          '✓ 3 luminárias spot de embutir em bom estado com lâmpadas funcionando',
          '✓ 8 tomadas e 4 interruptores em bom estado, funcionando',
          '✓ Janela de correr com vidro comum em bom estado',
          '✓ 1 ar condicionado split marca LG em bom estado, funcionando',
          '✓ 1 controle remoto do ar condicionado funcionando',
          '✓ 2 persianas rolo em bom estado',
        ],
        photos: SAINTPETER_PHOTOS.slice(2, 4).map((url, i) => ({
          dataUrl: url, name: `sala_estar_${i + 1}.jpg`, annotations: [],
        })),
      },
      {
        name: 'COZINHA',
        items: [
          '✓ Porta de correr de alumínio com vidro em bom estado',
          '✓ Paredes em alvenaria com azulejo branco em bom estado',
          '✓ Bancada de granito preto em bom estado com pequeno trincado no canto',
          '✓ Pia de aço inox em bom estado',
          '✓ Torneira flexível preta em bom estado, funcionando',
          '✓ 2 registros de água em bom estado, funcionando',
          '✓ Armários superiores em MDF branco em bom estado',
          '✓ Armários inferiores em MDF branco com puxadores em bom estado',
          '✓ Fogão 5 bocas marca Consul em bom estado, funcionando',
          '✓ Piso em cerâmica cinza em bom estado',
          '✓ Teto em gesso branco em bom estado',
          '✓ 1 luminária de embutir funcionando',
          '✓ 6 tomadas e 3 interruptores em bom estado',
          '✓ Ralo em bom estado',
          '✓ 1 registro de gás em bom estado',
        ],
        photos: SAINTPETER_PHOTOS.slice(4, 7).map((url, i) => ({
          dataUrl: url, name: `cozinha_${i + 1}.jpg`,
          annotations: i === 1 ? [{ x: 65, y: 35, label: 'Trincado na bancada' }] : [],
        })),
      },
      {
        name: 'QUARTO',
        items: [
          '✓ Porta de madeira em bom estado com pintura branca',
          '✓ Paredes em alvenaria com pintura nova em bom estado',
          '✓ Piso em laminado marrom em bom estado',
          '✓ Rodapé em madeira MDF branco em bom estado',
          '✓ Teto em gesso branco em bom estado',
          '✓ 2 luminárias spot em bom estado, funcionando',
          '✓ 4 tomadas e 2 interruptores em bom estado',
          '✓ Janela de correr de alumínio com vidro comum em bom estado',
          '✓ 1 persiana rolo em bom estado',
          '✓ 1 armário embutido 3 portas em MDF branco em bom estado',
        ],
        photos: SAINTPETER_PHOTOS.slice(8, 10).map((url, i) => ({
          dataUrl: url, name: `quarto_${i + 1}.jpg`, annotations: [],
        })),
      },
      {
        name: 'SUÍTE',
        items: [
          '✓ Porta de madeira em bom estado com pintura branca',
          '✓ Paredes em alvenaria com pintura nova em bom estado',
          '✓ Piso em laminado marrom em bom estado',
          '✓ Rodapé em madeira MDF branco em bom estado',
          '✓ Teto em gesso branco em bom estado',
          '✓ 3 luminárias LED spot em bom estado, funcionando',
          '✓ 6 tomadas e 3 interruptores em bom estado',
          '✓ Janela de correr com vidro comum em bom estado',
          '✓ 1 persiana rolo em bom estado',
          '✓ 1 closet embutido com 4 portas espelhadas em bom estado',
          '✓ Ar condicionado marca SAMSUNG inverter em bom estado, funcionando',
        ],
        photos: SAINTPETER_PHOTOS.slice(10, 12).map((url, i) => ({
          dataUrl: url, name: `suite_${i + 1}.jpg`, annotations: [],
        })),
      },
      {
        name: 'BANHEIRO SOCIAL',
        items: [
          '✓ Porta de madeira em bom estado com pintura branca',
          '✓ Vaso sanitário com caixa acoplada em bom estado, funcionando',
          '✓ Pia de louça com coluna de metal em bom estado',
          '✓ Torneira de metal cromado em bom estado, funcionando',
          '✓ Chuveiro elétrico marca Lorenzetti em bom estado, funcionando',
          '✓ Espelho sem moldura fixado em bom estado',
          '✓ Piso em cerâmica branca em bom estado',
          '✓ Paredes com azulejo até 1,5m em bom estado',
          '✓ Teto em gesso em bom estado',
          '✓ 1 luminária spot em bom estado',
          '✓ Box de vidro temperado em bom estado',
        ],
        photos: SAINTPETER_PHOTOS.slice(12, 14).map((url, i) => ({
          dataUrl: url, name: `banheiro_social_${i + 1}.jpg`, annotations: [],
        })),
      },
      {
        name: 'BANHEIRO SUÍTE',
        items: [
          '✓ Porta de madeira em bom estado com pintura branca',
          '✓ Box de vidro temperado com porta corrediça em bom estado',
          '✓ Pia de louça coríntia com coluna cromada em bom estado',
          '✓ Torneira de metal cromado em bom estado, funcionando',
          '✓ Chuveiro elétrico marca Lorenzetti com ducha de mão em bom estado',
          '✓ Vaso sanitário com caixa acoplada em bom estado',
          '✓ Espelho grande com moldura em MDF em bom estado',
          '✓ Piso em porcelanato cinza em bom estado',
          '✓ Paredes com azulejo branco até 2m em bom estado',
          '✓ Teto em gesso com 2 spots LED em bom estado',
          '✓ Aquecedor de água a gás marca Rinnai em bom estado, funcionando',
          '✓ 1 registro de água em bom estado',
        ],
        photos: SAINTPETER_PHOTOS.slice(14, 16).map((url, i) => ({
          dataUrl: url, name: `banheiro_suite_${i + 1}.jpg`, annotations: [],
        })),
      },
      {
        name: 'VARANDA',
        items: [
          '✓ Piso em cerâmica cinza em bom estado',
          '✓ Grade de proteção em alumínio pintado de branco em bom estado',
          '✓ Paredes em alvenaria com pintura em bom estado',
          '✓ Teto em concreto aparente em bom estado',
          '✓ 1 luminária externa em bom estado, funcionando',
          '✓ Porta de correr de alumínio com vidro em bom estado',
          '✓ Ralo em bom estado',
        ],
        photos: SAINTPETER_PHOTOS.slice(16, 18).map((url, i) => ({
          dataUrl: url, name: `varanda_${i + 1}.jpg`, annotations: [],
        })),
      },
    ],
    consideracoes: 'Conforme laudo, o imóvel encontra-se em bom estado de conservação. O estado do imóvel foi relatado acima de forma textual. O imóvel está sendo entregue com pintura nova nas paredes e com limpeza geral realizada. Foram testadas torneiras, vasos sanitários, chuveiros, interruptores e disjuntores, constatando que a parte hidráulica e elétrica está em perfeito funcionamento. Os ar-condicionados de todos os cômodos foram testados e estão operacionais. O aquecedor de água da suíte também foi testado com sucesso. Todas as portas, janelas e esquadrias foram verificadas quanto ao funcionamento.',
  };
}

export async function GET() {
  try {
    return NextResponse.json({
      success: true,
      examples: [
        { name: 'Columbus Tower - Sala Comercial', data: generateExample1() },
        { name: 'Saint Pierre - Apartamento 182', data: generateExample2() },
      ],
    });
  } catch (error) {
    return NextResponse.json({ error: 'Erro' }, { status: 500 });
  }
}
