/**
 * RBAC SYSTEM - PERMISSION CONSTANTS
 * "The Giant & Complete Matrix"
 * ImobWeb Elite 2026
 */

export const PERMISSIONS = {
  // --- PROPERTIES ---
  PROPERTIES_VIEW: 'properties:view',
  PROPERTIES_CREATE: 'properties:create',
  PROPERTIES_EDIT: 'properties:edit',
  PROPERTIES_DELETE: 'properties:delete',
  PROPERTIES_EXPORT: 'properties:export',
  PROPERTIES_MANAGE_PHOTOS: 'properties:manage_photos',
  PROPERTIES_VIEW_PRIVATE_DETAILS: 'properties:view_private_details', // Ex: Valor real do proprietário

  // --- LEADS ---
  LEADS_VIEW_ALL: 'leads:view_all',
  LEADS_VIEW_OWN: 'leads:view_own',
  LEADS_CREATE: 'leads:create',
  LEADS_EDIT: 'leads:edit',
  LEADS_DELETE: 'leads:delete',
  LEADS_EXPORT: 'leads:export',
  LEADS_ASSIGN: 'leads:assign',
  LEADS_CONVERT: 'leads:convert',

  // --- TEAM / USERS ---
  TEAM_VIEW: 'team:view',
  TEAM_MANAGE: 'team:manage',
  TEAM_PERMISSIONS_OVERRIDE: 'team:permissions_override',
  TEAM_VIEW_QUOTAS: 'team:view_quotas',

  // --- FINANCIAL (Agency Level) ---
  FINANCIAL_VIEW_INVOICES: 'financial:view_invoices',
  FINANCIAL_VIEW_REPORTS: 'financial:view_reports',
  FINANCIAL_MANAGE_PLANS: 'financial:manage_plans',
  FINANCIAL_VIEW_COMMISSIONS: 'financial:view_commissions',

  // --- MARKETING ---
  MARKETING_MANAGE_CAMPAIGNS: 'marketing:manage_campaigns',
  MARKETING_VIEW_ANALYTICS: 'marketing:view_analytics',
  MARKETING_SOCIAL_POST: 'marketing:social_post',

  // --- WHATSAPP / CONVERSATIONS ---
  WHATSAPP_VIEW_ALL: 'whatsapp:view_all',
  WHATSAPP_VIEW_OWN: 'whatsapp:view_own',
  WHATSAPP_SEND: 'whatsapp:send',
  WHATSAPP_CONFIG: 'whatsapp:config',

  // --- SYSTEM (PLATFORM ONLY) ---
  PLATFORM_MANAGE_TENANTS: 'platform:manage_tenants',
  PLATFORM_MANAGE_ADMINS: 'platform:manage_admins',
  PLATFORM_GLOBAL_ANALYTICS: 'platform:global_analytics',
  PLATFORM_BROADCAST: 'platform:broadcast',
  PLATFORM_BILLING_MASTER: 'platform:billing_master',
} as const;

export type PermissionKey = typeof PERMISSIONS[keyof typeof PERMISSIONS];

/**
 * DEFAULT ROLE TEMPLATES
 */
export const ROLE_TEMPLATES: Record<string, PermissionKey[]> = {
  // --- PLATFORM ROLES ---
  PLATFORM_MASTER: Object.values(PERMISSIONS), // Absolute access
  
  PLATFORM_MARKETING: [
    PERMISSIONS.PLATFORM_BROADCAST,
    PERMISSIONS.PLATFORM_GLOBAL_ANALYTICS,
    PERMISSIONS.MARKETING_VIEW_ANALYTICS,
    PERMISSIONS.TEAM_VIEW,
  ],
  
  PLATFORM_FINANCE: [
    PERMISSIONS.PLATFORM_BILLING_MASTER,
    PERMISSIONS.PLATFORM_GLOBAL_ANALYTICS,
    PERMISSIONS.FINANCIAL_VIEW_REPORTS,
    PERMISSIONS.TEAM_VIEW,
  ],
  
  PLATFORM_SUPPORT: [
    PERMISSIONS.PLATFORM_MANAGE_TENANTS,
    PERMISSIONS.PROPERTIES_VIEW,
    PERMISSIONS.LEADS_VIEW_ALL,
    PERMISSIONS.TEAM_VIEW,
  ],

  // --- AGENCY ROLES ---
  AGENCY_MASTER: [
    PERMISSIONS.PROPERTIES_VIEW, PERMISSIONS.PROPERTIES_CREATE, PERMISSIONS.PROPERTIES_EDIT, PERMISSIONS.PROPERTIES_DELETE, PERMISSIONS.PROPERTIES_EXPORT, PERMISSIONS.PROPERTIES_MANAGE_PHOTOS, PERMISSIONS.PROPERTIES_VIEW_PRIVATE_DETAILS,
    PERMISSIONS.LEADS_VIEW_ALL, PERMISSIONS.LEADS_CREATE, PERMISSIONS.LEADS_EDIT, PERMISSIONS.LEADS_DELETE, PERMISSIONS.LEADS_EXPORT, PERMISSIONS.LEADS_ASSIGN, PERMISSIONS.LEADS_CONVERT,
    PERMISSIONS.TEAM_VIEW, PERMISSIONS.TEAM_MANAGE, PERMISSIONS.TEAM_PERMISSIONS_OVERRIDE, PERMISSIONS.TEAM_VIEW_QUOTAS,
    PERMISSIONS.FINANCIAL_VIEW_INVOICES, PERMISSIONS.FINANCIAL_VIEW_REPORTS, PERMISSIONS.FINANCIAL_MANAGE_PLANS, PERMISSIONS.FINANCIAL_VIEW_COMMISSIONS,
    PERMISSIONS.MARKETING_MANAGE_CAMPAIGNS, PERMISSIONS.MARKETING_VIEW_ANALYTICS, PERMISSIONS.MARKETING_SOCIAL_POST,
    PERMISSIONS.WHATSAPP_VIEW_ALL, PERMISSIONS.WHATSAPP_SEND, PERMISSIONS.WHATSAPP_CONFIG,
  ],

  AGENCY_SALES: [
    PERMISSIONS.PROPERTIES_VIEW, PERMISSIONS.PROPERTIES_CREATE, PERMISSIONS.PROPERTIES_EDIT, PERMISSIONS.PROPERTIES_MANAGE_PHOTOS,
    PERMISSIONS.LEADS_VIEW_OWN, PERMISSIONS.LEADS_CREATE, PERMISSIONS.LEADS_EDIT, PERMISSIONS.LEADS_CONVERT,
    PERMISSIONS.WHATSAPP_VIEW_OWN, PERMISSIONS.WHATSAPP_SEND,
    PERMISSIONS.TEAM_VIEW,
  ],

  AGENCY_HR: [
    PERMISSIONS.TEAM_VIEW,
    PERMISSIONS.TEAM_MANAGE,
    PERMISSIONS.FINANCIAL_VIEW_COMMISSIONS,
  ],

  AGENCY_FINANCE: [
    PERMISSIONS.FINANCIAL_VIEW_INVOICES,
    PERMISSIONS.FINANCIAL_VIEW_REPORTS,
    PERMISSIONS.FINANCIAL_VIEW_COMMISSIONS,
    PERMISSIONS.TEAM_VIEW,
  ],

  AGENCY_MARKETING: [
    PERMISSIONS.PROPERTIES_VIEW,
    PERMISSIONS.MARKETING_MANAGE_CAMPAIGNS,
    PERMISSIONS.MARKETING_VIEW_ANALYTICS,
    PERMISSIONS.MARKETING_SOCIAL_POST,
    PERMISSIONS.TEAM_VIEW,
  ],

  AGENCY_SUPPORT: [
    PERMISSIONS.PROPERTIES_VIEW,
    PERMISSIONS.LEADS_VIEW_ALL,
    PERMISSIONS.TEAM_VIEW,
    PERMISSIONS.WHATSAPP_VIEW_ALL,
  ],
};
