import { PropertyCategory, PropertyTypeDefinition } from '../../types/property';

/**
 * imobWeb Property Type Configuration
 * mapping 50+ property types with specific logic and categories.
 */

export const PROPERTY_TYPES: PropertyTypeDefinition[] = [
  // --- RESIDENTIAL ---
  {
    id: 'APARTMENT',
    label: 'Apartamento',
    category: PropertyCategory.RESIDENTIAL,
    icon: 'building',
    requiredFields: ['bedrooms', 'bathrooms', 'usableArea'],
    suggestedFields: ['floor', 'totalFloors', 'condoFee'],
    availableFeatures: ['POOl', 'GYM', 'ELEVATOR', 'BALCONY'],
  },
  {
    id: 'HOUSE',
    label: 'Casa',
    category: PropertyCategory.RESIDENTIAL,
    icon: 'home',
    requiredFields: ['bedrooms', 'bathrooms', 'totalArea'],
    suggestedFields: ['yearBuilt', 'parkingSpots'],
    availableFeatures: ['BACKYARD', 'GARDEN', 'BBQ_AREA'],
  },
  {
    id: 'MANSION',
    label: 'Mansão',
    category: PropertyCategory.RESIDENTIAL,
    icon: 'crown',
    requiredFields: ['bedrooms', 'bathrooms', 'totalArea', 'suites'],
    suggestedFields: ['yearBuilt', 'parkingSpots', 'securityDetail'],
    availableFeatures: ['HOME_THEATER', 'WINE_CELLAR', 'HELIPAD'],
  },
  {
    id: 'LOFT',
    label: 'Loft',
    category: PropertyCategory.RESIDENTIAL,
    icon: 'box',
    requiredFields: ['usableArea', 'bathrooms'],
    suggestedFields: ['ceilingHeight'],
    availableFeatures: ['OPEN_PLAN', 'INDUSTRIAL_DESIGN'],
  },
  {
    id: 'STUDIO',
    label: 'Studio',
    category: PropertyCategory.RESIDENTIAL,
    icon: 'layout',
    requiredFields: ['usableArea', 'bathrooms'],
    suggestedFields: ['condoFee'],
    availableFeatures: ['CONCIERGE', 'LAUNDRY'],
  },
  {
    id: 'PENTHOUSE',
    label: 'Cobertura',
    category: PropertyCategory.RESIDENTIAL,
    icon: 'trending-up',
    requiredFields: ['bedrooms', 'bathrooms', 'usableArea'],
    suggestedFields: ['totalArea', 'condoFee'],
    availableFeatures: ['PRIVATE_POOL', 'VIEW', 'OUTDOOR_AREA'],
  },
  {
    id: 'TOWN_HOUSE',
    label: 'Sobrado',
    category: PropertyCategory.RESIDENTIAL,
    icon: 'layers',
    requiredFields: ['bedrooms', 'bathrooms', 'totalArea'],
    suggestedFields: ['parkingSpots'],
    availableFeatures: ['STAIRS', 'BALCONY'],
  },
  {
    id: 'KITNET',
    label: 'Kitnet',
    category: PropertyCategory.RESIDENTIAL,
    icon: 'square',
    requiredFields: ['usableArea', 'bathrooms'],
    suggestedFields: ['condoFee'],
    availableFeatures: ['FURNISHED'],
  },
  {
    id: 'FLAT',
    label: 'Flat',
    category: PropertyCategory.RESIDENTIAL,
    icon: 'bed',
    requiredFields: ['usableArea', 'bathrooms'],
    suggestedFields: ['condoFee', 'serviced'],
    availableFeatures: ['HOUSEKEEPING', 'VALET'],
  },
  {
    id: 'VILLA_HOUSE',
    label: 'Casa de Vila',
    category: PropertyCategory.RESIDENTIAL,
    icon: 'streets',
    requiredFields: ['totalArea', 'bedrooms'],
    suggestedFields: ['securityDetail'],
    availableFeatures: ['PRIVATE_STREET'],
  },
  {
    id: 'CONDO_HOUSE',
    label: 'Casa em Condomínio',
    category: PropertyCategory.RESIDENTIAL,
    icon: 'shield-check',
    requiredFields: ['totalArea', 'bedrooms', 'bathrooms'],
    suggestedFields: ['condoFee'],
    availableFeatures: ['GATED_SECURITY', 'CLUB_HOUSE'],
  },
  {
    id: 'DUPLEX',
    label: 'Duplex',
    category: PropertyCategory.RESIDENTIAL,
    icon: 'chevrons-up',
    requiredFields: ['usableArea', 'bedrooms'],
    suggestedFields: ['floor'],
    availableFeatures: ['INTERNAL_STAIRS', 'DOUBLE_CEILING'],
  },
  {
    id: 'TRIPLEX',
    label: 'Triplex',
    category: PropertyCategory.RESIDENTIAL,
    icon: 'layers-3',
    requiredFields: ['usableArea', 'bedrooms'],
    suggestedFields: ['floor'],
    availableFeatures: ['ELEVATOR', 'PRIVATE_ROOFTOP'],
  },

  // --- COMMERCIAL ---
  {
    id: 'OFFICE',
    label: 'Escritório',
    category: PropertyCategory.COMMERCIAL,
    icon: 'briefcase',
    requiredFields: ['usableArea', 'bathrooms'],
    suggestedFields: ['parkingSpots', 'meetingRooms'],
    availableFeatures: ['AC_READY', 'FIBER_OPTIC', 'RECEPTION'],
  },
  {
    id: 'STORE',
    label: 'Loja',
    category: PropertyCategory.COMMERCIAL,
    icon: 'shopping-bag',
    requiredFields: ['usableArea', 'totalArea'],
    suggestedFields: ['frontage', 'pedestrianTraffic'],
    availableFeatures: ['STREET_FRONT', 'SHOWCASE', 'STOCK_ROOM'],
  },
  {
    id: 'MEDICAL_OFFICE',
    label: 'Consultório',
    category: PropertyCategory.COMMERCIAL,
    icon: 'stethoscope',
    requiredFields: ['usableArea', 'bathrooms'],
    suggestedFields: ['accessibility'],
    availableFeatures: ['ANVISA_COMPLIANT', 'WAITING_ROOM'],
  },
  {
    id: 'COMMERCIAL_BUILDING',
    label: 'Prédio Comercial',
    category: PropertyCategory.COMMERCIAL,
    icon: 'building-2',
    requiredFields: ['totalArea', 'totalFloors'],
    suggestedFields: ['parkingSpots'],
    availableFeatures: ['ELEVATOR', 'SECURITY_GATE'],
  },
  {
    id: 'WAREHOUSE_COMMERCIAL',
    label: 'Galpão Comercial',
    category: PropertyCategory.COMMERCIAL,
    icon: 'warehouse',
    requiredFields: ['totalArea', 'ceilingHeight'],
    suggestedFields: ['dockingBays'],
    availableFeatures: ['TRUCK_ACCESS', 'OFFICE_ANNEX'],
  },
  {
    id: 'COWORKING_SPACE',
    label: 'Coworking',
    category: PropertyCategory.COMMERCIAL,
    icon: 'users',
    requiredFields: ['usableArea'],
    suggestedFields: ['stations'],
    availableFeatures: ['COMMON_KITCHEN', 'HIGH_SPEED_INTERNET'],
  },
  {
    id: 'HOTEL',
    label: 'Hotel',
    category: PropertyCategory.COMMERCIAL,
    icon: 'hotel',
    requiredFields: ['totalArea', 'bedrooms'],
    suggestedFields: ['stars'],
    availableFeatures: ['RESTAURANT', 'POOl', 'LAUNDRY'],
  },
  {
    id: 'RESTAURANT_SITE',
    label: 'Restaurante',
    category: PropertyCategory.COMMERCIAL,
    icon: 'utensils',
    requiredFields: ['usableArea'],
    suggestedFields: ['seatingCapacity'],
    availableFeatures: ['INDUSTRIAL_KITCHEN', 'GREASE_TRAP'],
  },

  // --- INDUSTRIAL ---
  {
    id: 'INDUSTRIAL_PLANT',
    label: 'Fábrica',
    category: PropertyCategory.INDUSTRIAL,
    icon: 'factory',
    requiredFields: ['totalArea', 'powerSupply'],
    suggestedFields: ['fireSafetyGrade'],
    availableFeatures: ['HEAVY_MACHINERY_FOUNDATION', 'SUBSTATION'],
  },
  {
    id: 'LOGISTIC_CENTER',
    label: 'Centro Logístico',
    category: PropertyCategory.INDUSTRIAL,
    icon: 'package',
    requiredFields: ['totalArea', 'dockingBays'],
    suggestedFields: ['pavementSpec'],
    availableFeatures: ['MANEUVER_YARD', 'FORKLIFT_PREP'],
  },

  // --- RURAL ---
  {
    id: 'FARM',
    label: 'Fazenda',
    category: PropertyCategory.RURAL,
    icon: 'tractor',
    requiredFields: ['totalArea', 'areaMeasurementUnit'],
    suggestedFields: ['waterAccess', 'soilQuality'],
    availableFeatures: ['CORRAL', 'SILO', 'MAIN_HOUSE', 'EMPLOYEE_HOUSING'],
  },
  {
    id: 'CHACARA',
    label: 'Chácara',
    category: PropertyCategory.RURAL,
    icon: 'leaf',
    requiredFields: ['totalArea'],
    suggestedFields: ['distanceFromCity'],
    availableFeatures: ['ORCHARD', 'WELL', 'POOL'],
  },
  {
    id: 'SITIO',
    label: 'Sítio',
    category: PropertyCategory.RURAL,
    icon: 'landscape',
    requiredFields: ['totalArea'],
    suggestedFields: ['cultivationType'],
    availableFeatures: ['STREAM', 'FENCED'],
  },
  {
    id: 'HARAS',
    label: 'Haras',
    category: PropertyCategory.RURAL,
    icon: 'horse',
    requiredFields: ['totalArea', 'stalls'],
    suggestedFields: ['trackQuality'],
    availableFeatures: ['TRAINING_RING', 'VETERINARY_ROOM'],
  },

  // --- DEVELOPMENT / LAND ---
  {
    id: 'RESIDENTIAL_LOT',
    label: 'Lote Residencial',
    category: PropertyCategory.DEVELOPMENT,
    icon: 'map',
    requiredFields: ['totalArea'],
    suggestedFields: ['terrainSlope'],
    availableFeatures: ['WATER_CONNECTED', 'ELECTRICITY_CONNECTED'],
  },
  {
    id: 'COMMERCIAL_LOT',
    label: 'Lote Comercial',
    category: PropertyCategory.DEVELOPMENT,
    icon: 'map-pin',
    requiredFields: ['totalArea'],
    suggestedFields: ['zoningLaw'],
    availableFeatures: ['HIGH_VISIBILITY'],
  },
  {
    id: 'INDUSTRIAL_LOT',
    label: 'Terreno Industrial',
    category: PropertyCategory.DEVELOPMENT,
    icon: 'map-pin-2',
    requiredFields: ['totalArea'],
    suggestedFields: ['powerAvailability'],
    availableFeatures: ['RAILWAY_ACCESS'],
  },

  // --- VACATION ---
  {
    id: 'BEACH_HOUSE',
    label: 'Casa de Praia',
    category: PropertyCategory.VACATION,
    icon: 'waves',
    requiredFields: ['bedrooms', 'bathrooms', 'totalArea'],
    suggestedFields: ['beachDistance'],
    availableFeatures: ['OCEAN_VIEW', 'SAND_WASH'],
  },
  {
    id: 'CHALET',
    label: 'Chalé',
    category: PropertyCategory.VACATION,
    icon: 'mountain',
    requiredFields: ['bedrooms', 'totalArea'],
    suggestedFields: ['heatingType'],
    availableFeatures: ['FIREPLACE', 'DECK'],
  },
  {
    id: 'CABIN',
    label: 'Cabana',
    category: PropertyCategory.VACATION,
    icon: 'tent',
    requiredFields: ['usableArea'],
    suggestedFields: ['offGridSource'],
    availableFeatures: ['ECO_FRIENDLY', 'WILDLIFE_VIEWING'],
  },
  {
    id: 'MOTORHOME_SITE',
    label: 'Vaga de Motorhome',
    category: PropertyCategory.VACATION,
    icon: 'truck',
    requiredFields: ['usableArea'],
    suggestedFields: ['hookupVoltage'],
    availableFeatures: ['WASTE_DISPOSAL', 'WIFI'],
  },
];

// Helper to get definition by ID
export const getPropertyType = (id: string) => PROPERTY_TYPES.find(t => t.id === id);

// Helper to filter by category
export const getTypesByCategory = (category: PropertyCategory) => 
  PROPERTY_TYPES.filter(t => t.category === category);
